services:
  rabbitmq:
    image: rabbitmq:3.12.4-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER?}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD?}
    ports:
      - "127.0.0.1:5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      start_period: 20s
      start_interval: 3s
      timeout: 15s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./conf.d/20-management.conf:/etc/rabbitmq/conf.d/20-management.conf:ro
    networks:
      - conversion_app

networks:
  conversion_app:
    name: conversion_app
    external: true

volumes:
  rabbitmq_data:
