services:
  rabbitmq:
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit tcp_listen_options [{backlog,4096},{nodelay,true},{linger,{true,0}},{exit_on_close,false},{keepalive,true}] log_levels [{connection,error},{default,error}] disk_free_limit 2147483648 handshake_timeout 60000 consumer_timeout 360000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq-http.rule=Host(`${RABBITMQ_SUBDOMAIN}.${BASE_DOMAIN}`)
      - traefik.http.routers.rabbitmq-http.entrypoints=http
      - traefik.http.routers.rabbitmq-http.middlewares=dashboard-ip-whitelist@file,redirect-to-https@file
      - traefik.http.routers.rabbitmq-https.rule=Host(`${RABBITMQ_SUBDOMAIN}.${BASE_DOMAIN}`)
      - traefik.http.routers.rabbitmq-https.entrypoints=https
      - traefik.http.routers.rabbitmq-https.middlewares=dashboard-ip-whitelist@file
      - traefik.http.routers.rabbitmq-https.tls=true
      - traefik.http.routers.rabbitmq-https.tls.certresolver=letsencrypt
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
