http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "*"
        accessControlAllowHeaders:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlAllowCredentials: true
        accessControlMaxAge: 86400
        addVaryHeader: true
    redirect-to-https:
      redirectScheme:
        scheme: https
    dashboard-ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "5.101.112.66/32" # vpn
          - "127.0.0.1/32"
    compress-response:
      compress: {}
    security-headers:
      headers:
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
    # Cache static assets (fonts, CSS, JS, images)
    cacheStaticAssets:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=31536000, immutable"
          Access-Control-Allow-Origin: "*"


  routers:
    dashboard:
      rule: "Host(`dashboard.dev.nambapp.ru`)"
      entryPoints:
        - https
      middlewares:
        - dashboard-ip-whitelist
      service: api@internal
      tls:
        certResolver: letsencrypt
