services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DOZZLE_HOSTNAME: ${APP_ENV}
      DOZZLE_NO_ANALYTICS: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle_data:/data
    networks:
      - conversion_app
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${BASE_DOMAIN}`)
      - traefik.http.routers.dozzle.entrypoints=https
      - traefik.http.routers.dozzle.middlewares=dashboard-ip-whitelist@file
      - traefik.http.routers.dozzle.tls.certresolver=letsencrypt
      - traefik.http.services.dozzle.loadbalancer.server.port=8080

networks:
  conversion_app:
    name: conversion_app
    external: true

volumes:
  dozzle_data:
